version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - C:\temp\api-pagamento-cartao\postgres:/var/lib/postgresql/data
    #   - C:\temp\card-pagamento-cartao\docker-entrypoint-initdb.d\cartoes.sql:/docker-entrypoint-initdb.d/cartoes.sql
    ports:
      - 2222:5432

  api:
    build:
      context: /home/wsl/git/card-payment-api/src/main/docker
      dockerfile: Dockerfile.jvm
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
